version: '2'

networks:
  saltbackend:

services:

  webapp:
    build: "./webapp"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Madrid
    ports:
      - "3000:3000"
    networks:
      saltbackend:

  saltmaster:
    build: "./saltmaster"
    ports:
      - "8080:8080"
    volumes:
      - "./saltmaster/etc-salt-master.d:/etc/salt/master.d"
      - "./saltmaster/srv-salt:/srv/salt"
      - "./saltmaster/srv-pillar:/srv/pillar"
      #- "./saltmaster/etc-salt-pki:/etc/salt/pki"
    networks:
      saltbackend:

  saltminionproxy:
    build: ./saltproxy
    volumes:
      - "./saltproxy/etc-salt/proxy:/etc/salt/proxy"
      #- "./saltproxy/etc-salt-pki:/etc/salt/pki" # save the key between relaunch
    networks:
      saltbackend:

    